// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDcyzVkV8u9N5Ia0Fl74GhBhdH9lh3Ffuw',
    appId: '1:457440405237:web:93a85fda3f536bae90c7bc',
    messagingSenderId: '457440405237',
    projectId: 'tutorly-fb826',
    authDomain: 'tutorly-fb826.firebaseapp.com',
    storageBucket: 'tutorly-fb826.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAF9QevN8Vdef9MwpMckgmBNuWLRfQfSeg',
    appId: '1:457440405237:android:ad0d9079097a1ce390c7bc',
    messagingSenderId: '457440405237',
    projectId: 'tutorly-fb826',
    storageBucket: 'tutorly-fb826.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAq5azrW1q5Yk3Oxg10XufgDX07buf1JRs',
    appId: '1:457440405237:ios:f21fafb7923f6cb490c7bc',
    messagingSenderId: '457440405237',
    projectId: 'tutorly-fb826',
    storageBucket: 'tutorly-fb826.firebasestorage.app',
    iosBundleId: 'com.example.tutorly',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAq5azrW1q5Yk3Oxg10XufgDX07buf1JRs',
    appId: '1:457440405237:ios:f21fafb7923f6cb490c7bc',
    messagingSenderId: '457440405237',
    projectId: 'tutorly-fb826',
    storageBucket: 'tutorly-fb826.firebasestorage.app',
    iosBundleId: 'com.example.tutorly',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDcyzVkV8u9N5Ia0Fl74GhBhdH9lh3Ffuw',
    appId: '1:457440405237:web:75b0bf04607e5d6a90c7bc',
    messagingSenderId: '457440405237',
    projectId: 'tutorly-fb826',
    authDomain: 'tutorly-fb826.firebaseapp.com',
    storageBucket: 'tutorly-fb826.firebasestorage.app',
  );
}
